apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-k8s-deployment
  labels:
    app: nest-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-k8s
  template:
    metadata:
      labels:
        app: nest-k8s
    spec:
      containers:
      - name: nest-k8s
        image: nest-k8s-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
